In [11]:
import pandas as pd

In [12]:
df1 = pd.read_csv("crop_dataset.csv")
df1

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Andaman and Nicobar,North and Middle Andaman,Mayabandar,Banana,Banana - Ripe,Medium,04/10/2024,30.0,50.0,40.0
1,Andaman and Nicobar,North and Middle Andaman,Mayabandar,Cowpea(Veg),Cowpea (Veg),FAQ,04/10/2024,50.0,80.0,60.0
2,Andaman and Nicobar,North and Middle Andaman,Mayabandar,Leafy Vegetable,Leafy Vegetables,FAQ,04/10/2024,30.0,50.0,40.0
3,Andhra Pradesh,Chittor,Madanapalli,Tomato,Local,FAQ,04/10/2024,7000.0,8800.0,8200.0
4,Andhra Pradesh,Guntur,Duggirala,Turmeric,Finger,FAQ,04/10/2024,10311.0,12350.0,11800.0
...,...,...,...,...,...,...,...,...,...,...
15793,West Bengal,Puruliya,Purulia,Brinjal,Other,FAQ,04/10/2024,2800.0,3600.0,3200.0
15794,West Bengal,Puruliya,Purulia,Onion,Other,FAQ,04/10/2024,4100.0,4600.0,4300.0
15795,West Bengal,Puruliya,Purulia,Rice,Other,FAQ,04/10/2024,3600.0,3630.0,3600.0
15796,West Bengal,Sounth 24 Parganas,Baruipur(Canning),Onion,Other,FAQ,04/10/2024,4625.0,4825.0,4725.0
15797,West Bengal,Sounth 24 Parganas,Diamond Harbour(South 24-pgs),Fish,Katla(Big),FAQ,04/10/2024,16500.0,17500.0,17000.0

In [13]:
df2 = pd.read_csv("weather_data.csv")
df2

,timestamp,city,temperature,humidity,pressure,weather,wind_speed,season
0,2024-10-15 12:20:12.493037,Guntur,30.93,80,1009,overcast clouds,1.94,Autumn
1,2024-10-15 12:20:13.629545,Visakhapatnam,29.94,84,1009,light rain,1.03,Autumn
2,2024-10-15 12:20:14.759140,Barpeta,29.73,57,1009,clear sky,1.80,Autumn
3,2024-10-15 12:20:15.874307,Cachar,17.05,93,1018,broken clouds,1.28,Autumn
4,2024-10-15 12:20:16.885105,Goalpara,29.74,60,1009,clear sky,0.76,Autumn
...,...,...,...,...,...,...,...,...
307,2024-10-15 12:27:30.046699,Jalgaon,31.56,59,1009,broken clouds,2.25,Autumn
308,2024-10-15 12:27:31.210570,Kalimpong,24.58,81,1011,broken clouds,1.27,Autumn
309,2024-10-15 12:27:33.907693,Mungeli,31.50,59,1009,broken clouds,0.76,Autumn
310,2024-10-15 12:27:36.128457,Surajpur,30.15,40,1010,clear sky,2.12,Autumn
311,2024-10-15 12:27:37.469894,Bellary,24.35,85,1010,overcast clouds,2.09,Autumn

In [14]:
merged_df = pd.merge(df1, df2, left_on='District', right_on='city', how='inner')
merged_df

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price,timestamp,city,temperature,humidity,pressure,weather,wind_speed,season
0,Andhra Pradesh,Guntur,Duggirala,Turmeric,Finger,FAQ,04/10/2024,10311.0,12350.0,11800.0,2024-10-15 12:20:12.493037,Guntur,30.93,80,1009,overcast clouds,1.94,Autumn
1,Andhra Pradesh,Guntur,Tenali,Black Gram (Urd Beans)(Whole),Black Gram (Whole),FAQ,04/10/2024,8400.0,8600.0,8500.0,2024-10-15 12:20:12.493037,Guntur,30.93,80,1009,overcast clouds,1.94,Autumn
2,Andhra Pradesh,Guntur,Tenali,Lemon,Lemon,FAQ,04/10/2024,3000.0,4500.0,3800.0,2024-10-15 12:20:12.493037,Guntur,30.93,80,1009,overcast clouds,1.94,Autumn
3,Andhra Pradesh,Guntur,Duggirala,Turmeric,Bulb,FAQ,04/10/2024,10311.0,12350.0,11800.0,2024-10-15 12:20:12.493037,Guntur,30.93,80,1009,overcast clouds,1.94,Autumn
4,Andhra Pradesh,Visakhapatnam,Anakapally,Gur(Jaggery),NO 3,FAQ,04/10/2024,3100.0,3310.0,3205.0,2024-10-15 12:20:13.629545,Visakhapatnam,29.94,84,1009,light rain,1.03,Autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12063,West Bengal,Kalimpong,Kalimpong,Rice,Other,FAQ,04/10/2024,4000.0,5000.0,4500.0,2024-10-15 12:27:31.210570,Kalimpong,24.58,81,1011,broken clouds,1.27,Autumn
12064,Chattisgarh,Mungeli,Lormi,Paddy(Dhan)(Common),I.R. 36,FAQ,04/10/2024,1800.0,1800.0,1800.0,2024-10-15 12:27:33.907693,Mungeli,31.50,59,1009,broken clouds,0.76,Autumn
12065,Chattisgarh,Surajpur,Surajpur,Mahua,Other,FAQ,04/10/2024,3000.0,3000.0,3000.0,2024-10-15 12:27:36.128457,Surajpur,30.15,40,1010,clear sky,2.12,Autumn
12066,Karnataka,Bellary,Kottur,Groundnut,Natte,FAQ,04/10/2024,1529.0,7350.0,5042.0,2024-10-15 12:27:37.469894,Bellary,24.35,85,1010,overcast clouds,2.09,Autumn
12067,Karnataka,Bellary,Kottur,Sunflower,Hybrid,FAQ,04/10/2024,3050.0,6679.0,5119.0,2024-10-15 12:27:37.469894,Bellary,24.35,85,1010,overcast clouds,2.09,Autumn

In [15]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12068 entries, 0 to 12067
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              12068 non-null  object
 1   District           12068 non-null  object
 2   Market             12068 non-null  object
 3   Commodity          12068 non-null  object
 4   Variety            12068 non-null  object
 5   Grade              12068 non-null  object
 6   Arrival_Date       12068 non-null  object
 7   Min_x0020_Price    12068 non-null  float64
 8   Max_x0020_Price    12068 non-null  float64
 9   Modal_x0020_Price  12068 non-null  float64
 10  timestamp          12068 non-null  object
 11  city               12068 non-null  object
 12  temperature        12068 non-null  float64
 13  humidity           12068 non-null  int64
 14  pressure           12068 non-null  int64
 15  weather            12068 non-null  object
 16  wind_speed         12068 non-null  float64
 17  season             12068 non-null  object
dtypes: float64(5), int64(2), object(11)
memory usage: 1.7+ MB

 ### Data Processing

In [16]:
df = merged_df

In [17]:
df = df.rename(columns={'Min_x0020_Price': 'Min_Price', 'Max_x0020_Price': 'Max_Price', 'Modal_x0020_Price': 'Frequent_price'})

In [18]:
# Convert prices from quintals to kilograms by dividing by 100 and update the existing columns
df['Min_Price'] = df['Min_Price'] / 100
df['Max_Price'] = df['Max_Price'] / 100
df['Frequent_price'] = df['Frequent_price'] / 100

In [19]:
df.drop(columns = ['city', 'season', 'timestamp', 'Arrival_Date'], inplace = True)

In [20]:
exclude_columns = ['wind_speed']

# Convert all decimal values to integers except for the specified columns
for column in df.columns:
    if column not in exclude_columns and pd.api.types.is_numeric_dtype(df[column]):
        df[column] = df[column].round(0).astype(int)

### Feature Engineering

In [21]:
# Price Range
df['Price_Range'] = df['Max_Price'] - df['Min_Price']

In [22]:
# Average Price
df['Average_Price'] = (df['Min_Price'] + df['Max_Price']) / 2

# Price Variability Index
df['Price_Variability'] = (df['Frequent_price'] - df['Average_Price']) / df['Average_Price']

# Round Price_Variability to 4 decimal places
df['Price_Variability'] = df['Price_Variability'].round(4)

In [23]:
# Weather Condition Indicator
df['Weather_Condition'] = df['weather'].apply(lambda x: 'Favorable' if 'clear' in x or 'sunny' in x else 'Unfavorable')

In [24]:
df.head()

,State,District,Market,Commodity,Variety,Grade,Min_Price,Max_Price,Frequent_price,temperature,humidity,pressure,weather,wind_speed,Price_Range,Average_Price,Price_Variability,Weather_Condition
0,Andhra Pradesh,Guntur,Duggirala,Turmeric,Finger,FAQ,103,124,118,31,80,1009,overcast clouds,1.94,21,113.5,0.0396,Unfavorable
1,Andhra Pradesh,Guntur,Tenali,Black Gram (Urd Beans)(Whole),Black Gram (Whole),FAQ,84,86,85,31,80,1009,overcast clouds,1.94,2,85.0,0.0000,Unfavorable
2,Andhra Pradesh,Guntur,Tenali,Lemon,Lemon,FAQ,30,45,38,31,80,1009,overcast clouds,1.94,15,37.5,0.0133,Unfavorable
3,Andhra Pradesh,Guntur,Duggirala,Turmeric,Bulb,FAQ,103,124,118,31,80,1009,overcast clouds,1.94,21,113.5,0.0396,Unfavorable
4,Andhra Pradesh,Visakhapatnam,Anakapally,Gur(Jaggery),NO 3,FAQ,31,33,32,30,84,1009,light rain,1.03,2,32.0,0.0000,Unfavorable

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12068 entries, 0 to 12067
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              12068 non-null  object
 1   District           12068 non-null  object
 2   Market             12068 non-null  object
 3   Commodity          12068 non-null  object
 4   Variety            12068 non-null  object
 5   Grade              12068 non-null  object
 6   Min_Price          12068 non-null  int32
 7   Max_Price          12068 non-null  int32
 8   Frequent_price     12068 non-null  int32
 9   temperature        12068 non-null  int32
 10  humidity           12068 non-null  int32
 11  pressure           12068 non-null  int32
 12  weather            12068 non-null  object
 13  wind_speed         12068 non-null  float64
 14  Price_Range        12068 non-null  int32
 15  Average_Price      12068 non-null  float64
 16  Price_Variability  12044 non-null  float64
 17  Weather_Condition  12068 non-null  object
dtypes: float64(3), int32(7), object(8)
memory usage: 1.3+ MB

In [26]:
df.to_csv("crops_prices.csv", index=False)